extends:
  - standard-with-typescript
  - airbnb/hooks
  - plugin:@typescript-eslint/recommended
  - '@unocss'
parser: '@typescript-eslint/parser'
parserOptions:
  project: './tsconfig.json'
settings:
  import/parsers:
    '@typescript-eslint/parser': [.ts, .tsx]
  import/resolver:
    typescript:
      alwaysTryTypes: true
rules:
  comma-dangle: [error, always-multiline]
  import/order: [error, {
    groups: [builtin, external, internal, [parent, sibling, index, object]],
    newlines-between: always,
    alphabetize: { order: asc }
  }]
  jsx-quotes: [error, prefer-double]
  '@typescript-eslint/indent': [error, 4]
  '@typescript-eslint/explicit-function-return-type': off
  '@typescript-eslint/restrict-template-expressions': off
  '@typescript-eslint/strict-boolean-expressions': off
  '@typescript-eslint/no-non-null-assertion': off
  '@typescript-eslint/consistent-type-assertions': off
  '@typescript-eslint/promise-function-async': off
  '@typescript-eslint/no-floating-promises': off
  '@typescript-eslint/no-invalid-void-type': off
  '@typescript-eslint/no-misused-promises': off
  '@typescript-eslint/no-confusing-void-expression': off
  '@typescript-eslint/comma-dangle': [error, only-multiline]
